### ISSUE TITLE
Checking filenames on ingest

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#443]
There is a validation process now that checks that uploaded files have corresponding metadata, however, it is too lenient on case associations of filenames. It needs to reject files that are not named _exactly_ as per the catalog.

**Comment by JonoGillett** [comment]
I have modified the ingest to required a case sensitive match, but left everything else as-is for now. 


This is apparently due to the underlying database, MySQL, being case insensitive by default.
Would you prefer that I change the identifier columns in the database (for collection and item tables) to use a case-sensitive data type? I don't know if this will affect anything else throughout the app (e.g. searching) so I haven't investigated further down that path at this stage.

**Comment by nthieberger** [comment]
I think it needs to be case sensitive as this is the most restrictive scenario and one that does occur (as we have seen) in various parts of the system, so it should be enforced.

**Comment by enwardy** [comment]
@JonoGillett was this completed?

**Comment by AmandaPDSC** [comment]
@nthieberger I think this is now addressed by the Azoulay scripts - can this be closed now?

**Comment by nthieberger** [comment]
There is an outstanding issue of the case of extensions which need to be converted to lowercase. If that is now addressed by the resolution of this issue that is fine.

**Comment by NickWardPDSC** [comment]
looks like uppercase file extensions still got through to the catalog after NickT's last comment above, 
e.g.
LPF-WD053-IMG_01A.TIF (and others in this item), modified 31/5/2018
JK1-REB202001b-M01.MP4
JK1-REB202001b-M03.MP4 , both modified 26/10/2022

**Comment by johnf** [comment]
New ingest system deals with this
