### ISSUE TITLE
Automated authentication

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#498]
Is it possible to allow a remote service to access the catalog as an ordinary logged in user? This would allow us to build services that can call media, for example, without having to copy the media elsewhere.

**Comment by JonoGillett** [comment]
Without investigating further this seems like a perfect candidate for the 'modularisation' that we've discussed before. A separate web service designed for external system access, rather than user access might be more appropriate, as well as avoiding adding performance issues with NABU.

However this is all very speculative and it would be worthwhile discussing your actual use cases for this. Some potential issues I can think of right now:
* would the service pass through credentials from an end user, or would it have its own?
* if it has its own, it would show results that it could see, regardless of the end user (unless they re-implemented the same access controls, which would be redundant and hard to enforce)
** If the service access was higher than the user's, they would see things they couldn't in Nabu
** If the service access was lower than the user's, they would miss things that they could normally see

These may or may not be problems, but from experience it's better to consider them up front when starting to expose data to external services.

**Comment by nthieberger** [comment]
Yes, good idea about modularisation, can we discuss at our next meeting.

**Comment by johnf** [comment]
We have API functionality now with API keys that we can use when or if this is needed
