### ISSUE TITLE
Rif-cs feed error

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#679]
It seems that some private items are being exposed by this feed. RDA shows this collection but shouldn't: https://researchdata.ands.org.au/nicktest/967720/?refer_q=rows=15/sort=score%20desc/class=collection/p=1/q=paradisec/
However, other private collections are not being exposed (e.g. AP4, AP5)

**Comment by tom-h** [comment]
It looks to me that the rif-cs feed is possibly broken anyway:

http://catalog.paradisec.org.au/oai/collection?verb=ListRecords&metadataPrefix=rif

**Comment by tom-h** [comment]
It's been broken since mid-October.

**Comment by enwardy** [comment]
https://github.com/nabu-catalog/nabu/issues/400

**Comment by AmandaPDSC** [comment]
We have been notified again by ARDC about this error, RDA Registry error in the data source (for the last incremental harvest) says:  _HTTP Error 500: Internal Server Error Error while trying (5) times to connect to url:http://catalog.paradisec.org.au/oai/collection?verb=ListRecords&metadataPrefix=rif&from=2018-10-12T17:44:14Z&until=2019-04-15T18:00:08Z _ 

And records have apparently not be harvested since October

**Comment by johnf** [comment]
OAI is currently working
